#!/bin/bash

dirty=$(git status --porcelain | wc -l)
if [ $dirty -gt 0 ] 
then
	echo "Commiting"
	git add -A && git commit -m "site [ci skip]"
	if [ $? -ne 0 ]
	then
		exit $?
	fi
else
	echo "Nothing to commit."
fi
git push
if [ $? -ne 0 ]
then
		exit $?
fi


echo "Building Jekyll site..."

rm -rf javadoc
mkdir javadoc
cp -r ../capsule/build/docs/javadoc/ javadoc/capsule
cp -r ../capsule-util/build/docs/javadoc/ javadoc/capsule-util

jekyll build && s3_website push
